# pre-commit configuration file
# Ref: https://pre-commit.com/


repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace


  # Pylint
  # https://pylint.readthedocs.io/en/latest/user_guide/installation/pre-commit-integration.html
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args: [ "--rcfile=pyproject.toml" ]

  # mypy
  #
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.4.1'
    hooks:
      - id: mypy
        args: ['--strict', '--ignore-missing-imports', '--config-file pyproject.toml']

  # isort - format imports
  # https://pycqa.github.io/isort/docs/configuration/pre-commit.html
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--settings-path", "pyproject.toml"]


  # Black - code formatter
  # https://black.readthedocs.io/en/stable/integrations/source_version_control.html
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black-jupyter


  # Conventional commits
  # https://github.com/compilerla/conventional-pre-commit





