# Drafts your next Release notes as Pull Requests are merged into "master"


name: 'Release Drafter'

on:
  workflow_call:


jobs:

  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:

      - name: 'Release drafter'
        # https://github.com/release-drafter/release-drafter
        uses: release-drafter/release-drafter@v5
        with:
         config-name: config/release_drafter.yaml
         publish: false
         prerelease: false
         disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
